name: "AlarmServer"
description: "My first real add-on!"
version: "1.0.0"
slug: "example"
advanced: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
hassio_role: manager  
#ingress: true
init: false  
  
  
startup: before
ports:
  15002/tcp: 15002
  21/tcp: 21
  #8000/tcp: 8000  
map:
  - config:rw
options:
  debug: false  
  hisilicon:
   - enabled: false  
     port: 15002
  mqtt:
   - enabled: true
     username: alarmserver
     password: "password"
     port: 1883
     server: "mqtt.example.com"
     topicroot: camera-alerts 
  ftp:
   - enabled: true
     port: 21
     password: "root"
     allowFiles: true
     rootPath: "./ftp"   
schema:
  debug: bool 
  hisilicon:
   - enabled: bool  
     port: int
  mqtt:
   - enabled: bool 
     username: str
     password: str
     port: int
     server: str
     topicroot: str   
  ftp:
   - enabled: bool
     port: int
     password: str
     allowFiles: bool
     rootPath: str   
